Repository kymatio/kymatio, pull requests merged in 2018-12, with the labels that each got.

#246 API Change coeff order
  kymatio/scattering2d/scattering2d.py
  kymatio/scattering2d/tests/test_scattering2d.py
Labels: 2D

#247 API Change coefficient order
  kymatio/scattering1d/scattering1d.py
  kymatio/scattering1d/tests/test_scattering1d.py
Labels: 1D

#275 Add code coverage.
  .travis.yml
Labels: enhancement
