Repository kymatio/kymatio, pull requests merged in 2019-03, with the labels that each got.

#360 TST Test raised errors in `Scattering2D.forward`
  kymatio/scattering2d/tests/test_scattering2d.py
Labels: 2D

#346 FIX bug on the input sizes
  kymatio/scattering2d/backend/backend_skcuda.py
  kymatio/scattering2d/backend/backend_torch.py
  kymatio/scattering2d/scattering2d.py
  kymatio/scattering2d/tests/test_scattering2d.py
Labels: 2D, bug

#320 ENH Use real filterbank in Scattering2D
  kymatio/scattering2d/backend/backend_skcuda.py
  kymatio/scattering2d/backend/backend_torch.py
  kymatio/scattering2d/filter_bank.py
  kymatio/scattering2d/tests/test_scattering2d.py
Labels: 2D, enhancement

#345 ENH Torch backend isn't necessary for creating filters
  kymatio/scattering2d/backend/backend_skcuda.py
  kymatio/scattering2d/backend/backend_torch.py
  kymatio/scattering2d/filter_bank.py
  kymatio/scattering2d/scattering2d.py
Labels: 2D, enhancement
