Repository kymatio/kymatio, pull requests merged in 2020-01, with the labels that each got.

#475 update README, announce v0.2.a0 [ci skip]
  README.md
Labels: doc

#485 MAINT no longer pass unknown globals and locals
  kymatio/scattering2d/frontend/__init__.py
Labels: 2D, enhancement

#509 FFT SciPy
  kymatio/scattering1d/backend/numpy_backend.py
  kymatio/scattering1d/filter_bank.py
  kymatio/scattering2d/backend/numpy_backend.py
  kymatio/scattering2d/filter_bank.py
Labels: API, enhancement

#534 TensorFlow 3D
  kymatio/scattering3d/backend/tensorflow_backend.py
  kymatio/scattering3d/frontend/tensorflow_frontend.py
  kymatio/scattering3d/tests/test_tensorflow_scattering3d.py
Labels: 3D, API
