Repository kymatio/kymatio, pull requests merged in 2022-06, with the labels that each got.

#842 MAINT decouple `scattering_filter_factory` from `ScatteringBase1D.build`
  examples/1d/plot_filters.py
  kymatio/scattering1d/filter_bank.py
  kymatio/scattering1d/frontend/base_frontend.py
  kymatio/scattering1d/utils.py
  tests/scattering1d/test_numpy_scattering1d.py
Labels: 1D

#848 MAINT simplify `compute_params_filterbank`, remove `_move_one_dyadic_step`
  kymatio/scattering1d/filter_bank.py
Labels: 1D

#850 MAINT remove `calibrate_scattering_filters`
  kymatio/scattering1d/filter_bank.py
  kymatio/scattering1d/frontend/base_frontend.py
  kymatio/scattering1d/utils.py
  tests/scattering1d/test_filters_scattering1d.py
  tests/scattering1d/test_torch_scattering1d.py
Labels: 1D

#863 MAINT deprecate `self.N` and `self.J_pad` in 1D
  kymatio/scattering1d/filter_bank.py
  kymatio/scattering1d/frontend/base_frontend.py
  kymatio/scattering1d/utils.py
  tests/scattering1d/test_numpy_scattering1d.py
  tests/scattering1d/test_utils_scattering1d.py
Labels: 1D

#883 MAINT make `Scattering2D` compatible with TF>=2.5
  kymatio/scattering2d/core/scattering2d.py
  kymatio/scattering2d/filter_bank.py
  kymatio/scattering2d/frontend/torch_frontend.py
Labels: 2D

#876 move core 1D asserts to `_check_filterbanks` in `ScatteringBase`
  kymatio/frontend/base_frontend.py
  kymatio/scattering1d/core/scattering1d.py
  kymatio/scattering1d/frontend/base_frontend.py
Labels: 1D

#887 check `oversampling` in 1D
  kymatio/scattering1d/frontend/base_frontend.py
  tests/scattering1d/test_torch_scattering1d.py
Labels: 1D

#886 Deprecate `self.N` in 2D
  kymatio/scattering2d/frontend/base_frontend.py
  kymatio/scattering2d/frontend/numpy_frontend.py
  kymatio/scattering2d/frontend/tensorflow_frontend.py
  kymatio/scattering2d/frontend/torch_frontend.py
  tests/scattering2d/test_torch_scattering2d.py
Labels: 2D

#820 DOC Output shape documentation
  doc/source/userguide.rst
Labels: good first issue, 1D, 2D, 3D
